"""Default categories and rules for BudgetFlow Tracker."""

from __future__ import annotations

DEFAULT_CATEGORIES = [
    {"name": "Food & Drink", "description": "Groceries, restaurants, dining out", "is_income": False},
    {"name": "Transportation", "description": "Gas, transit, rideshare, parking", "is_income": False},
    {"name": "Shopping", "description": "Retail purchases, online shopping", "is_income": False},
    {"name": "Entertainment", "description": "Movies, streaming, events, hobbies", "is_income": False},
    {"name": "Bills & Utilities", "description": "Electric, water, internet, phone bills", "is_income": False},
    {"name": "Healthcare", "description": "Medical expenses, prescriptions, insurance", "is_income": False},
    {"name": "Income", "description": "Salary, freelance, investment income", "is_income": True},
    {"name": "Other", "description": "Miscellaneous transactions", "is_income": False},
]

DEFAULT_RULES = [
    {"name": "Grocery Store Match", "pattern": "grocery", "pattern_type": "contains", "category": "Food & Drink", "priority": 10, "confidence": 0.9},
    {"name": "Whole Foods", "pattern": "whole foods", "pattern_type": "contains", "category": "Food & Drink", "priority": 10, "confidence": 0.95},
    {"name": "Trader Joe's", "pattern": "trader joe", "pattern_type": "contains", "category": "Food & Drink", "priority": 10, "confidence": 0.95},
    {"name": "Walmart Grocery", "pattern": "walmart grocery", "pattern_type": "contains", "category": "Food & Drink", "priority": 10, "confidence": 0.9},
    {"name": "Safeway", "pattern": "safeway", "pattern_type": "contains", "category": "Food & Drink", "priority": 10, "confidence": 0.95},
    {"name": "Kroger", "pattern": "kroger", "pattern_type": "contains", "category": "Food & Drink", "priority": 10, "confidence": 0.95},
    {"name": "Restaurant General", "pattern": "restaurant", "pattern_type": "contains", "category": "Food & Drink", "priority": 5, "confidence": 0.7},
    {"name": "Starbucks", "pattern": "starbucks", "pattern_type": "contains", "category": "Food & Drink", "priority": 10, "confidence": 0.95},
    {"name": "McDonald's", "pattern": "mcdonald", "pattern_type": "contains", "category": "Food & Drink", "priority": 10, "confidence": 0.95},
    {"name": "Subway", "pattern": "subway", "pattern_type": "contains", "category": "Food & Drink", "priority": 10, "confidence": 0.95},
    {"name": "Gas Station", "pattern": "gas station", "pattern_type": "contains", "category": "Transportation", "priority": 5, "confidence": 0.7},
    {"name": "Shell Gas", "pattern": "shell", "pattern_type": "contains", "category": "Transportation", "priority": 10, "confidence": 0.9},
    {"name": "Uber", "pattern": "uber", "pattern_type": "contains", "category": "Transportation", "priority": 10, "confidence": 0.95},
    {"name": "Lyft", "pattern": "lyft", "pattern_type": "contains", "category": "Transportation", "priority": 10, "confidence": 0.95},
    {"name": "Transit", "pattern": "transit", "pattern_type": "contains", "category": "Transportation", "priority": 10, "confidence": 0.9},
    {"name": "MTA", "pattern": "mta", "pattern_type": "contains", "category": "Transportation", "priority": 10, "confidence": 0.95},
    {"name": "Amazon", "pattern": "amazon", "pattern_type": "contains", "category": "Shopping", "priority": 10, "confidence": 0.95},
    {"name": "Target", "pattern": "target", "pattern_type": "contains", "category": "Shopping", "priority": 10, "confidence": 0.95},
    {"name": "Walmart", "pattern": "walmart", "pattern_type": "contains", "category": "Shopping", "priority": 10, "confidence": 0.95},
    {"name": "Best Buy", "pattern": "best buy", "pattern_type": "contains", "category": "Shopping", "priority": 10, "confidence": 0.95},
    {"name": "Electric Company", "pattern": "electric", "pattern_type": "contains", "category": "Bills & Utilities", "priority": 5, "confidence": 0.7},
    {"name": "Water Company", "pattern": "water", "pattern_type": "contains", "category": "Bills & Utilities", "priority": 5, "confidence": 0.7},
    {"name": "Internet Provider", "pattern": "internet", "pattern_type": "contains", "category": "Bills & Utilities", "priority": 5, "confidence": 0.7},
    {"name": "Phone Company", "pattern": "phone", "pattern_type": "contains", "category": "Bills & Utilities", "priority": 5, "confidence": 0.7},
    {"name": "Netflix", "pattern": "netflix", "pattern_type": "contains", "category": "Bills & Utilities", "priority": 10, "confidence": 0.95},
    {"name": "Spotify", "pattern": "spotify", "pattern_type": "contains", "category": "Bills & Utilities", "priority": 10, "confidence": 0.95},
    {"name": "Insurance Payment", "pattern": "insurance", "pattern_type": "contains", "category": "Bills & Utilities", "priority": 5, "confidence": 0.7},
    {"name": "CVS Pharmacy", "pattern": "cvs pharmacy", "pattern_type": "contains", "category": "Healthcare", "priority": 10, "confidence": 0.95},
    {"name": "Walgreens", "pattern": "walgreens", "pattern_type": "contains", "category": "Healthcare", "priority": 10, "confidence": 0.95},
    {"name": "Hospital", "pattern": "hospital", "pattern_type": "contains", "category": "Healthcare", "priority": 10, "confidence": 0.9},
    {"name": "Doctor Office", "pattern": "doctor", "pattern_type": "contains", "category": "Healthcare", "priority": 10, "confidence": 0.9},
    {"name": "Direct Deposit", "pattern": "direct deposit", "pattern_type": "contains", "category": "Income", "priority": 10, "confidence": 0.95},
    {"name": "Payroll", "pattern": "payroll", "pattern_type": "contains", "category": "Income", "priority": 10, "confidence": 0.95},
    {"name": "Freelance Payment", "pattern": "freelance", "pattern_type": "contains", "category": "Income", "priority": 10, "confidence": 0.9},
    {"name": "Refund", "pattern": "refund", "pattern_type": "contains", "category": "Income", "priority": 5, "confidence": 0.7},
    {"name": "Interest Income", "pattern": "interest", "pattern_type": "contains", "category": "Income", "priority": 5, "confidence": 0.7},
    {"name": "Dividend", "pattern": "dividend", "pattern_type": "contains", "category": "Income", "priority": 5, "confidence": 0.7},
    {"name": "Transfer In", "pattern": "transfer in", "pattern_type": "contains", "category": "Income", "priority": 5, "confidence": 0.6},
]
