"""
planner.py — Orchestrates agentic commerce workflows based on a gameplan.
"""
from __future__ import annotations
import json
import textwrap
import urllib.request
from datetime import datetime, timezone
from typing import Any

_OLLAMA_HOST = "http://localhost:11434"

def _call_ollama(prompt: str, model: str = "qwen3:6b", timeout: int = 180) -> str:
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
        "options": {"temperature": 0.2, "num_ctx": 4096},
    }
    try:
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            f"{_OLLAMA_HOST}/api/generate",
            data=data, headers={"Content-Type": "application/json"}, method="POST",
        )
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8")).get("response", "").strip()
    except Exception:
        return ""

def _parse_json(text: str) -> dict:
    start = text.find("{")
    end   = text.rfind("}") + 1
    if start >= 0 and end > start:
        try:
            return json.loads(text[start:end])
        except json.JSONDecodeError:
            pass
    return {}

def _fallback_workflows(gameplan_text: str) -> dict:
    return {
        "title": "Agentic Commerce Workflows (Fallback)",
        "workflows": [
            {
                "agent_role": "Sourcing Agent",
                "tasks": ["Find suppliers", "Negotiate pricing"]
            },
            {
                "agent_role": "Storefront Agent",
                "tasks": ["Generate product descriptions", "Deploy Shopify template"]
            },
            {
                "agent_role": "Marketing Agent",
                "tasks": ["Create ad copy based on gameplan", "Launch initial test campaign"]
            }
        ],
        "metadata": {"model": "fallback", "generated_at": datetime.now(timezone.utc).isoformat()}
    }

def orchestrate_workflows(gameplan_text: str, model: str = "qwen3:6b") -> dict[str, Any]:
    prompt = textwrap.dedent(f"""
        You are the Master Agentic Commerce Planner.
        Given the following dropshipping business gameplan, break it down into specific
        autonomous workflows to be executed by specialized AI agents.

        Return ONLY a valid JSON object matching this schema:
        {{
          "title": "Workflow Plan Title",
          "workflows": [
            {{
              "agent_role": "Role (e.g., 'Sourcing Agent')",
              "tasks": ["Specific actionable task 1", "Specific actionable task 2"]
            }}
          ]
        }}

        GAMEPLAN:
        {gameplan_text[:8000]}
    """).strip()

    response = _call_ollama(prompt, model=model)
    result = _parse_json(response)

    if not result or "workflows" not in result:
        return _fallback_workflows(gameplan_text)

    result["metadata"] = {
        "model": model,
        "generated_at": datetime.now(timezone.utc).isoformat()
    }
    return result


def format_markdown(data: dict) -> str:
    lines = [
        f"# 🤖 DropGentic Plan: {data.get('title', 'Unknown')}", "",
    ]
    
    for wf in data.get("workflows", []):
        lines.append(f"## {wf.get('agent_role', 'Agent')}")
        for t in wf.get("tasks", []):
            lines.append(f"- [ ] {t}")
        lines.append("")
        
    lines.append(f"*(Generated by DropGentic at {data.get('metadata', {}).get('generated_at', '')[:10]})*")
    return "\n".join(lines)
