"""Rule validation module for validating generated rules."""

from typing import Any, Dict, List

from email_tool.agent.base import AgentResult
from email_tool.models import Rule, RuleType


class RuleValidator:
    """
    Validates rule dictionaries before they are applied.
    
    This ensures that rules generated by the LLM or created by users
    conform to the expected schema and are safe to apply.
    """
    
    def __init__(self):
        """Initialize the rule validator."""
        self.errors: List[str] = []
        self.warnings: List[str] = []
    
    def validate_rules(self, rules: List[Dict[str, Any]]) -> AgentResult:
        """
        Validate a list of rule dictionaries.
        
        Args:
            rules: List of rule dictionaries to validate.
        
        Returns:
            AgentResult with validation status and any errors/warnings.
        """
        self.errors = []
        self.warnings = []
        
        if not isinstance(rules, list):
            return AgentResult(
                success=False,
                data=None,
                error_message="Rules must be a list"
            )
        
        if not rules:
            self.warnings.append("No rules provided")
            return AgentResult(
                success=True,
                data=[],
                metadata={"warnings": self.warnings}
            )
        
        validated_rules = []
        seen_names = set()
        for i, rule_data in enumerate(rules):
            rule_result = self._validate_single_rule(rule_data, i, seen_names)
            if rule_result["valid"]:
                validated_rules.append(rule_data)
            else:
                self.errors.extend(rule_result["errors"])
        
        result = AgentResult(
            success=len(self.errors) == 0,
            data=validated_rules,
            metadata={
                "total_rules": len(rules),
                "valid_rules": len(validated_rules),
                "errors": self.errors,
                "warnings": self.warnings
            }
        )
        
        return result
    
    def _validate_single_rule(self, rule_data: Dict[str, Any], index: int, seen_names: set) -> Dict[str, Any]:
        """
        Validate a single rule dictionary.
        
        Args:
            rule_data: The rule dictionary to validate.
            index: The index of the rule in the list (for error messages).
            seen_names: Set of rule names already seen (for duplicate detection).
        
        Returns:
            Dictionary with 'valid' boolean and 'errors' list.
        """
        result = {"valid": True, "errors": []}
        rule_name = rule_data.get("name", f"rule_{index}")
        
        # Check for duplicate names
        if rule_name in seen_names:
            result["errors"].append(f"Rule '{rule_name}': duplicate rule name")
            result["valid"] = False
        else:
            seen_names.add(rule_name)
        
        # Check required fields
        if "name" not in rule_data:
            result["errors"].append(f"Rule at index {index}: missing required field 'name'")
            result["valid"] = False
        
        if "type" not in rule_data:
            result["errors"].append(f"Rule '{rule_name}': missing required field 'type'")
            result["valid"] = False
        else:
            # Validate rule type
            try:
                RuleType(rule_data["type"])
            except ValueError:
                result["errors"].append(
                    f"Rule '{rule_name}': invalid rule type '{rule_data['type']}'"
                )
                result["valid"] = False
        
        # Validate category - required field
        if "category" not in rule_data:
            result["errors"].append(
                f"Rule '{rule_name}': missing required field 'category'"
            )
            result["valid"] = False
        else:
            # Category must be a non-empty string
            if not isinstance(rule_data["category"], str) or not rule_data["category"].strip():
                result["errors"].append(
                    f"Rule '{rule_name}': category must be a non-empty string"
                )
                result["valid"] = False
        
        # Check pattern/value based on rule type
        if "type" in rule_data and result["valid"]:
            rule_type = rule_data["type"]
            has_pattern = "pattern" in rule_data
            has_value = "value" in rule_data
            
            if rule_type in [
                RuleType.FROM_EXACT.value, RuleType.FROM_PATTERN.value,
                RuleType.SUBJECT_EXACT.value, RuleType.SUBJECT_CONTAINS.value,
                RuleType.SUBJECT_PATTERN.value, RuleType.BODY_CONTAINS_EXACT.value,
                RuleType.BODY_CONTAINS_CONTAINS.value, RuleType.BODY_CONTAINS_PATTERN.value
            ]:
                if not has_pattern and not has_value:
                    result["errors"].append(
                        f"Rule '{rule_name}': missing required field 'pattern'"
                    )
                    result["valid"] = False
                elif has_pattern:
                    # Validate regex pattern
                    import re
                    try:
                        import re
                        re.compile(rule_data["pattern"])
                    except re.error as e:
                        result["errors"].append(
                            f"Rule '{rule_name}': invalid regex pattern '{rule_data['pattern']}': {e}"
                        )
                        result["valid"] = False
            
            if rule_type == RuleType.HAS_ATTACHMENT.value:
                if has_pattern:
                    result["errors"].append(
                        f"Rule '{rule_name}': has_attachment type should not have 'pattern'"
                    )
                    result["valid"] = False
        
        # Check priority if provided
        if "priority" in rule_data:
            priority_value = rule_data["priority"]
            if not isinstance(priority_value, int) or isinstance(priority_value, bool):
                result["errors"].append(
                    f"Rule '{rule_name}': priority must be an integer"
                )
                result["valid"] = False
            else:
                priority = int(priority_value)
                if priority < 0 or priority > 100:
                    result["errors"].append(
                        f"Rule '{rule_name}': priority must be between 0 and 100"
                    )
                    result["valid"] = False
        
        # Check for deprecated fields
        if "value" in rule_data:
            result["warnings"].append(
                f"Rule '{rule_name}': 'value' field is deprecated, use 'pattern' instead"
            )
        
        return result
    
    def validate_rule_from_model(self, rule: Rule) -> AgentResult:
        """
        Validate a Rule object.
        
        Args:
            rule: The Rule object to validate.
        
        Returns:
            AgentResult with validation status.
        """
        rule_dict = {
            "name": rule.name,
            "type": rule.rule_type.value,
            "pattern": rule.pattern,
            "priority": rule.priority,
            "category": rule.category
        }
        
        result = self._validate_single_rule(rule_dict, -1)
        
        return AgentResult(
            success=result["valid"],
            data=rule if result["valid"] else None,
            metadata={"errors": result["errors"]}
        )
