"""
mcp_factory v0 — wrap verified capabilities as local stdio JSONL MCP servers.

Layout under PIPELINE_DIR:
  mcps/mcp_{slug}/server.py
  mcps/mcp_{slug}/manifest.json   (mcp_manifest.v1)
  mcps/mcp_{slug}/smoke_report.json

Factory is a separate loop from the software factory: scaffold + smoke +
best-effort registry insert. Does not invent product code — only wraps an
existing capability_slug via pipeline.capability_tools.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from pipeline.paths import get_pipeline_dir, mcps_dir
from pipeline.pipeline_config import PROJECT_ROOT

SCHEMA = "mcp_manifest.v1"
TRANSPORT = "stdio_jsonl"
TOOLS = ["ping", "describe", "invoke"]

__all__ = [
    "SCHEMA",
    "TRANSPORT",
    "TOOLS",
    "mcp_slug_for",
    "mcp_dir",
    "is_mcp_smoked",
    "wrap_capability_as_mcp",
    "smoke_mcp",
    "register_mcp",
    "list_mcps",
    "drain_queue",
]


def _iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def mcp_slug_for(capability_slug: str) -> str:
    """Normalize capability slug to mcp_ prefix form."""
    s = (capability_slug or "").strip()
    if not s:
        raise ValueError("capability_slug is required")
    if s.startswith("mcp_"):
        return s
    return f"mcp_{s}"


def mcp_dir(mcp_slug: str) -> Path:
    """Return mcps/{mcp_slug}/ (does not create)."""
    return mcps_dir() / mcp_slug_for(mcp_slug)


def _capability_from_mcp_slug(mcp_slug: str) -> str:
    s = (mcp_slug or "").strip()
    if s.startswith("mcp_"):
        return s[4:]
    return s


def _server_template(capability_slug: str, mcp_slug: str) -> str:
    """Generate a self-contained stdio JSONL server for one capability."""
    # Escape for embedding in source as string literals
    cap = capability_slug.replace("\\", "\\\\").replace('"', '\\"')
    mslug = mcp_slug.replace("\\", "\\\\").replace('"', '\\"')
    return f'''#!/usr/bin/env python3
"""Auto-generated MCP stdio JSONL server for capability `{cap}`.

Methods: ping, describe, invoke.
Transport: one JSON object per stdin line -> one JSON response per stdout line.
Generated by pipeline.mcp_factory — re-run wrap to regenerate.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

WRAPS_CAPABILITY = "{cap}"
MCP_SLUG = "{mslug}"


def _ensure_factory_path() -> None:
    """Allow import of pipeline.* when launched under PIPELINE_DIR/mcps/."""
    candidates = []
    for key in ("MCP_FACTORY_ROOT", "AICOMPETE_ROOT", "IDEA_IMPL_ROOT"):
        v = (os.environ.get(key) or "").strip()
        if v:
            candidates.append(v)
    # Walk up a few parents looking for a package root that has pipeline/
    here = Path(__file__).resolve().parent
    for p in [here, *here.parents[:6]]:
        if (p / "pipeline" / "__init__.py").is_file():
            candidates.append(str(p))
    for c in candidates:
        if c and c not in sys.path:
            sys.path.insert(0, c)


_ensure_factory_path()


def _handle(req: dict) -> dict:
    method = (req.get("method") or "").strip()
    params = req.get("params") or {{}}
    if not isinstance(params, dict):
        params = {{}}

    if method == "ping":
        return {{"ok": True, "result": "mcp-ok", "mcp_slug": MCP_SLUG}}

    if method == "describe":
        # Always ok=True so smoke can pass without a live registry row.
        try:
            from pipeline.capability_tools import describe_capability

            text = describe_capability(WRAPS_CAPABILITY)
            if not text:
                text = f"capability {{WRAPS_CAPABILITY}}: (empty describe)"
            return {{
                "ok": True,
                "result": text,
                "wraps_capability": WRAPS_CAPABILITY,
                "mcp_slug": MCP_SLUG,
            }}
        except Exception as exc:
            return {{
                "ok": True,
                "result": f"unknown capability {{WRAPS_CAPABILITY}}: {{exc}}",
                "wraps_capability": WRAPS_CAPABILITY,
                "mcp_slug": MCP_SLUG,
            }}

    if method == "invoke":
        args = params.get("args", "")
        if args is None:
            args = ""
        args = str(args)
        cwd = str(params.get("cwd") or "")
        try:
            from pipeline.capability_tools import invoke_capability

            out = invoke_capability(WRAPS_CAPABILITY, args=args, cwd=cwd)
            # capability_tools returns ERROR: ... strings on failure
            ok = not str(out).startswith("ERROR:")
            return {{
                "ok": ok,
                "result": out,
                "wraps_capability": WRAPS_CAPABILITY,
                "mcp_slug": MCP_SLUG,
            }}
        except Exception as exc:
            return {{"ok": False, "error": str(exc), "mcp_slug": MCP_SLUG}}

    return {{"ok": False, "error": f"unknown method: {{method}}", "mcp_slug": MCP_SLUG}}


def main() -> None:
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            req = json.loads(line)
        except json.JSONDecodeError as exc:
            sys.stdout.write(json.dumps({{"ok": False, "error": str(exc)}}) + "\\n")
            sys.stdout.flush()
            continue
        if not isinstance(req, dict):
            sys.stdout.write(
                json.dumps({{"ok": False, "error": "request must be a JSON object"}}) + "\\n"
            )
            sys.stdout.flush()
            continue
        resp = _handle(req)
        sys.stdout.write(json.dumps(resp, ensure_ascii=False) + "\\n")
        sys.stdout.flush()


if __name__ == "__main__":
    main()
'''


def wrap_capability_as_mcp(
    capability_slug: str,
    *,
    entrypoint: str | None = None,
    cwd: str | None = None,
    force: bool = False,
) -> dict:
    """Scaffold mcps/mcp_{slug}/server.py + manifest.json.

    Returns mcp_manifest.v1 as a dict. If the MCP dir already exists and
    *force* is False, reloads and returns the existing manifest (rewriting
    only missing pieces). Server always implements ping/describe/invoke;
    invoke routes through capability_tools.invoke_capability.
    """
    cap = (capability_slug or "").strip()
    if not cap:
        raise ValueError("capability_slug is required")
    # Allow passing mcp_foo as capability: strip prefix for wraps_capability
    if cap.startswith("mcp_"):
        wraps = cap[4:]
        mslug = cap
    else:
        wraps = cap
        mslug = f"mcp_{cap}"

    root = mcps_dir()
    root.mkdir(parents=True, exist_ok=True)
    d = root / mslug
    d.mkdir(parents=True, exist_ok=True)

    server_path = d / "server.py"
    manifest_path = d / "manifest.json"

    if manifest_path.is_file() and not force:
        try:
            existing = json.loads(manifest_path.read_text(encoding="utf-8"))
            if existing.get("schema") == SCHEMA and (d / "server.py").is_file():
                # Keep existing; note skip when already smoked (drain safety)
                if str(existing.get("status") or "") in ("smoked", "verified"):
                    existing = dict(existing)
                    existing["skipped"] = True
                    existing["skip_reason"] = "already_smoked"
                return existing
        except (json.JSONDecodeError, OSError):
            pass

    server_path.write_text(
        _server_template(wraps, mslug),
        encoding="utf-8",
        newline="\n",
    )

    try:
        server_rel = str(server_path.relative_to(get_pipeline_dir())).replace("\\", "/")
    except ValueError:
        server_rel = str(server_path)

    status = "draft"
    if (d / "smoke_report.json").is_file() and not force:
        try:
            sr = json.loads((d / "smoke_report.json").read_text(encoding="utf-8"))
            if sr.get("ok"):
                status = "smoked"
        except (json.JSONDecodeError, OSError):
            pass

    manifest: dict[str, Any] = {
        "schema": SCHEMA,
        "mcp_slug": mslug,
        "wraps_capability": wraps,
        "transport": TRANSPORT,
        "server_path": server_rel,
        "tools": list(TOOLS),
        "status": status,
        "created_at": _iso(),
    }
    if entrypoint:
        manifest["entrypoint_override"] = entrypoint
    if cwd:
        manifest["cwd_override"] = cwd

    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return manifest


def _load_manifest(mcp_slug: str) -> dict[str, Any] | None:
    path = mcp_dir(mcp_slug) / "manifest.json"
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def _save_manifest(manifest: dict[str, Any]) -> Path:
    mslug = str(manifest.get("mcp_slug") or "")
    path = mcp_dir(mslug) / "manifest.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return path


def _rpc_line(proc: subprocess.Popen, req: dict, *, timeout_s: float) -> dict:
    """Write one JSON-L request and read one JSON-L response."""
    assert proc.stdin is not None and proc.stdout is not None
    line = json.dumps(req, ensure_ascii=False) + "\n"
    proc.stdin.write(line)
    proc.stdin.flush()
    # readline with overall process timeout handled by caller
    out = proc.stdout.readline()
    if not out:
        raise RuntimeError("MCP server closed stdout without response")
    return json.loads(out)


def is_mcp_smoked(mcp_slug: str) -> bool:
    """True if manifest status is smoked/verified and server.py exists."""
    mslug = mcp_slug_for(mcp_slug)
    d = mcp_dir(mslug)
    if not (d / "server.py").is_file():
        return False
    man = _load_manifest(mslug)
    if not man:
        return False
    return str(man.get("status") or "") in ("smoked", "verified")


def smoke_mcp(
    mcp_slug: str,
    *,
    timeout_s: float = 15.0,
    require_invoke: bool = False,
    invoke_args: str = "--help",
    skip_if_smoked: bool = False,
    force: bool = False,
) -> dict:
    """Spawn server.py; ping + describe required; optional invoke oracle.

    Writes smoke_report.json next to the server. Records goal_trace
    mode=mcp_factory.

    *require_invoke*: also require method invoke with *invoke_args* (default
    ``--help``) to return ok. Use for real capability quality bar.
    *skip_if_smoked*: if already smoked/verified and not *force*, return prior
    report without re-spawning (drain-queue bulk safety).
    """
    mslug = mcp_slug_for(mcp_slug)
    d = mcp_dir(mslug)
    server = d / "server.py"

    if skip_if_smoked and not force and is_mcp_smoked(mslug):
        prior: dict[str, Any] = {
            "ok": True,
            "mcp_slug": mslug,
            "skipped": True,
            "skip_reason": "already_smoked",
            "server_path": str(server),
            "ts": _iso(),
            "manifest_status": (_load_manifest(mslug) or {}).get("status"),
        }
        # Prefer last smoke_report if present
        sr = d / "smoke_report.json"
        if sr.is_file():
            try:
                old = json.loads(sr.read_text(encoding="utf-8"))
                if isinstance(old, dict) and old.get("ok"):
                    prior["prior_smoke"] = {
                        "ts": old.get("ts"),
                        "checks": [
                            c.get("method") for c in (old.get("checks") or [])
                        ],
                    }
            except (json.JSONDecodeError, OSError):
                pass
        return prior

    if not server.is_file():
        report = {
            "ok": False,
            "mcp_slug": mslug,
            "error": f"server.py missing under {d}",
            "ts": _iso(),
        }
        d.mkdir(parents=True, exist_ok=True)
        (d / "smoke_report.json").write_text(
            json.dumps(report, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        _trace_smoke(mslug, report)
        return report

    env = os.environ.copy()
    factory_root = str(PROJECT_ROOT.resolve())
    env["MCP_FACTORY_ROOT"] = factory_root
    # Ensure pipeline package is importable
    existing_pp = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = (
        factory_root + (os.pathsep + existing_pp if existing_pp else "")
    )
    # Keep caller's PIPELINE_DIR if set; else bind to live get_pipeline_dir
    env.setdefault("PIPELINE_DIR", str(get_pipeline_dir()))
    env.setdefault("PIPELINE_LEGACY", "0")

    checks: list[dict[str, Any]] = []
    ok = True
    error: str | None = None
    proc: subprocess.Popen | None = None
    try:
        proc = subprocess.Popen(
            [sys.executable, "-u", str(server)],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            env=env,
            cwd=str(d),
        )
        # ping
        try:
            ping_resp = _rpc_line(
                proc, {"method": "ping", "params": {}}, timeout_s=timeout_s
            )
            ping_ok = bool(ping_resp.get("ok"))
            checks.append({"method": "ping", "ok": ping_ok, "resp": ping_resp})
            if not ping_ok:
                ok = False
                error = f"ping failed: {ping_resp}"
        except Exception as exc:
            ok = False
            error = f"ping error: {exc}"
            checks.append({"method": "ping", "ok": False, "error": str(exc)})

        # describe (must ok=True even if capability unknown)
        if ok:
            try:
                desc_resp = _rpc_line(
                    proc, {"method": "describe", "params": {}}, timeout_s=timeout_s
                )
                desc_ok = bool(desc_resp.get("ok"))
                checks.append(
                    {"method": "describe", "ok": desc_ok, "resp": desc_resp}
                )
                if not desc_ok:
                    ok = False
                    error = error or f"describe failed: {desc_resp}"
            except Exception as exc:
                ok = False
                error = error or f"describe error: {exc}"
                checks.append({"method": "describe", "ok": False, "error": str(exc)})

        # invoke oracle (optional hard fail)
        if ok:
            inv_args = (invoke_args if invoke_args is not None else "--help") or ""
            try:
                inv_resp = _rpc_line(
                    proc,
                    {"method": "invoke", "params": {"args": inv_args}},
                    timeout_s=timeout_s,
                )
                inv_ok = bool(inv_resp.get("ok"))
                checks.append(
                    {
                        "method": "invoke",
                        "ok": inv_ok,
                        "args": inv_args,
                        "resp": inv_resp,
                    }
                )
                if require_invoke and not inv_ok:
                    ok = False
                    error = error or f"invoke failed: {inv_resp}"
            except Exception as exc:
                checks.append(
                    {
                        "method": "invoke",
                        "ok": False,
                        "args": inv_args,
                        "error": str(exc),
                    }
                )
                if require_invoke:
                    ok = False
                    error = error or f"invoke error: {exc}"
    except Exception as exc:
        ok = False
        error = str(exc)
    finally:
        if proc is not None:
            try:
                if proc.stdin:
                    proc.stdin.close()
            except Exception:
                pass
            try:
                proc.kill()
            except Exception:
                pass
            try:
                proc.wait(timeout=3)
            except Exception:
                pass
            # capture residual stderr for diagnostics
            try:
                if proc.stderr:
                    err_tail = proc.stderr.read()
                    if err_tail and not ok:
                        error = (error or "") + f" | stderr: {err_tail[:500]}"
            except Exception:
                pass

    report: dict[str, Any] = {
        "ok": ok,
        "mcp_slug": mslug,
        "server_path": str(server),
        "checks": checks,
        "ts": _iso(),
        "timeout_s": timeout_s,
        "require_invoke": bool(require_invoke),
        "invoke_args": invoke_args if require_invoke or any(
            c.get("method") == "invoke" for c in checks
        ) else None,
    }
    if error:
        report["error"] = error

    (d / "smoke_report.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    # Bump manifest status on success
    manifest = _load_manifest(mslug)
    if manifest is not None:
        if ok:
            manifest["status"] = "smoked"
            manifest["smoked_at"] = report["ts"]
            if require_invoke:
                manifest["invoke_oracle"] = {
                    "args": invoke_args,
                    "ok": True,
                    "at": report["ts"],
                }
        else:
            # keep draft/prior; note last smoke failure
            manifest["last_smoke_ok"] = False
            manifest["last_smoke_at"] = report["ts"]
        _save_manifest(manifest)
        report["manifest_status"] = manifest.get("status")

    _trace_smoke(mslug, report)
    return report


def _trace_smoke(mcp_slug: str, report: dict[str, Any]) -> None:
    """Best-effort goal_trace.v1 with mode=mcp_factory."""
    try:
        from pipeline.goal_trace import append_event, finalize_trace, start_trace

        wraps = _capability_from_mcp_slug(mcp_slug)
        plan = [
            {"step": 1, "intent": "ping", "tool": "mcp.ping"},
            {"step": 2, "intent": "describe", "tool": "mcp.describe"},
        ]
        if any(c.get("method") == "invoke" for c in (report.get("checks") or [])):
            plan.append({"step": 3, "intent": "invoke", "tool": "mcp.invoke"})
        tr = start_trace(
            f"MCP factory smoke for {mcp_slug} (wraps {wraps})",
            goal_id=f"mcp_smoke_{uuid.uuid4().hex[:10]}",
            mode="mcp_factory",
            plan=plan,
        )
        for ch in report.get("checks") or []:
            append_event(
                tr,
                type="tool",
                tool=f"mcp.{ch.get('method', '?')}",
                args={"mcp_slug": mcp_slug},
                result_snip=json.dumps(ch, ensure_ascii=False)[:1500],
                ok=bool(ch.get("ok")),
            )
        status = "goal_proven" if report.get("ok") else "goal_failed"
        finalize_trace(
            tr,
            status=status,
            oracle={
                "name": "mcp_smoke",
                "pass": bool(report.get("ok")),
                "evidence": report.get("error") or f"smoke ok for {mcp_slug}",
            },
            train_weight=1.0 if report.get("ok") else 0.1,
        )
        report["goal_trace_id"] = tr.get("goal_id")
    except Exception as exc:
        report["goal_trace_error"] = str(exc)


def register_mcp(manifest: dict) -> None:
    """Best-effort insert into capability registry as kind=mcp.

    Writes nothing extra if registry is unavailable; never raises on API
    mismatch — records a note on the manifest when possible.
    """
    if not isinstance(manifest, dict):
        return
    mslug = str(manifest.get("mcp_slug") or "").strip()
    wraps = str(manifest.get("wraps_capability") or _capability_from_mcp_slug(mslug))
    if not mslug:
        return

    server_path = str(manifest.get("server_path") or f"mcps/{mslug}/server.py")
    status = str(manifest.get("status") or "draft")
    # Map factory statuses onto registry statuses
    reg_status = "verified" if status in ("smoked", "verified") else "draft"
    purpose = f"stdio JSONL MCP wrapper for capability {wraps}"
    entry = f"python {server_path}"
    note = "registry_skipped"

    try:
        from pipeline.capability_registry import registry_db

        # Ensure parent dir + schema via _connect if available
        try:
            from pipeline.capability_registry import _connect, _now  # type: ignore

            conn = _connect()
            conn.execute(
                """
                INSERT INTO capabilities (
                    slug, title, kind, status, purpose, domains, entrypoint, import_path,
                    cwd_template, requires, example_invoke, source_project,
                    phase, total_phases, updated_at
                ) VALUES (?, ?, 'mcp', ?, ?, '["mcp"]', ?, '', ?, '[]', ?, ?, 0, 0, ?)
                ON CONFLICT(slug) DO UPDATE SET
                    title=excluded.title,
                    kind='mcp',
                    status=excluded.status,
                    purpose=excluded.purpose,
                    entrypoint=excluded.entrypoint,
                    cwd_template=excluded.cwd_template,
                    example_invoke=excluded.example_invoke,
                    source_project=excluded.source_project,
                    updated_at=excluded.updated_at
                """,
                (
                    mslug,
                    f"MCP: {wraps}",
                    reg_status,
                    purpose,
                    entry,
                    f"mcps/{mslug}",
                    f'echo \'{{"method":"ping"}}\' | python {server_path}',
                    wraps,
                    _now(),
                ),
            )
            conn.commit()
            conn.close()
            note = "registry_ok"
        except Exception as exc:
            # Fallback: raw sqlite if helpers differ
            try:
                import sqlite3

                db = registry_db()
                db.parent.mkdir(parents=True, exist_ok=True)
                conn = sqlite3.connect(db)
                conn.execute(
                    """
                    CREATE TABLE IF NOT EXISTS capabilities (
                        slug TEXT PRIMARY KEY,
                        title TEXT NOT NULL,
                        kind TEXT NOT NULL,
                        status TEXT NOT NULL,
                        purpose TEXT DEFAULT '',
                        domains TEXT DEFAULT '[]',
                        entrypoint TEXT DEFAULT '',
                        import_path TEXT DEFAULT '',
                        cwd_template TEXT DEFAULT '',
                        requires TEXT DEFAULT '[]',
                        example_invoke TEXT DEFAULT '',
                        source_project TEXT DEFAULT '',
                        phase INTEGER DEFAULT 0,
                        total_phases INTEGER DEFAULT 0,
                        updated_at TEXT NOT NULL
                    )
                    """
                )
                conn.execute(
                    """
                    INSERT INTO capabilities (
                        slug, title, kind, status, purpose, domains, entrypoint,
                        import_path, cwd_template, requires, example_invoke,
                        source_project, phase, total_phases, updated_at
                    ) VALUES (?, ?, 'mcp', ?, ?, '["mcp"]', ?, '', ?, '[]', ?, ?, 0, 0, ?)
                    ON CONFLICT(slug) DO UPDATE SET
                        status=excluded.status, purpose=excluded.purpose,
                        entrypoint=excluded.entrypoint, updated_at=excluded.updated_at
                    """,
                    (
                        mslug,
                        f"MCP: {wraps}",
                        reg_status,
                        purpose,
                        entry,
                        f"mcps/{mslug}",
                        f'echo \'{{"method":"ping"}}\' | python {server_path}',
                        wraps,
                        _iso(),
                    ),
                )
                conn.commit()
                conn.close()
                note = "registry_ok_raw"
            except Exception as exc2:
                note = f"registry_skip: {exc}; {exc2}"
    except Exception as exc:
        note = f"registry_skip: {exc}"

    # Annotate manifest (best-effort, non-fatal)
    try:
        manifest["registry_note"] = note
        if mslug:
            live = _load_manifest(mslug) or dict(manifest)
            live["registry_note"] = note
            _save_manifest(live)
    except Exception:
        pass


def list_mcps() -> list[dict]:
    """List mcp_manifest.v1 dicts under mcps/ (sorted by mcp_slug)."""
    root = mcps_dir()
    if not root.is_dir():
        return []
    out: list[dict] = []
    for child in sorted(root.iterdir()):
        if not child.is_dir():
            continue
        man = child / "manifest.json"
        if not man.is_file():
            continue
        try:
            data = json.loads(man.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        if isinstance(data, dict):
            out.append(data)
    out.sort(key=lambda m: str(m.get("mcp_slug") or ""))
    return out


def drain_queue(
    *,
    limit: int = 1,
    require_invoke: bool = True,
    invoke_args: str = "--help",
    skip_if_smoked: bool = True,
) -> list[dict]:
    """For each pending mcp_factory job (up to *limit*): wrap + smoke + mark_done.

    Skips re-work when MCP already smoked (*skip_if_smoked*). By default runs
    invoke oracle with ``--help`` (*require_invoke*).

    Returns a list of result dicts (one per job processed).
    """
    from pipeline.mcp_queue import list_pending, load_job, mark_done

    results: list[dict] = []
    pending = list_pending()[: max(0, int(limit))]
    for job_path in pending:
        try:
            job = load_job(job_path)
        except Exception as exc:
            results.append({"ok": False, "error": f"load_job: {exc}", "job_path": str(job_path)})
            try:
                mark_done(job_path, {"ok": False, "error": str(exc)})
            except Exception:
                pass
            continue

        cap = str(job.get("capability_slug") or "").strip()
        job_id = job.get("job_id")
        if not cap:
            res = {"ok": False, "error": "missing capability_slug", "job_id": job_id}
            mark_done(job_path, res)
            results.append(res)
            continue

        try:
            mslug = mcp_slug_for(cap)
            if skip_if_smoked and is_mcp_smoked(mslug):
                man = _load_manifest(mslug) or {"mcp_slug": mslug, "status": "smoked"}
                res = {
                    "ok": True,
                    "skipped": True,
                    "skip_reason": "already_smoked",
                    "job_id": job_id,
                    "capability_slug": cap,
                    "mcp_slug": mslug,
                    "manifest": man,
                }
                mark_done(job_path, res)
                results.append(res)
                continue

            manifest = wrap_capability_as_mcp(cap)
            mslug = str(manifest.get("mcp_slug") or mslug)
            smoke = smoke_mcp(
                mslug,
                require_invoke=require_invoke,
                invoke_args=invoke_args,
                skip_if_smoked=False,
            )
            try:
                register_mcp(
                    manifest
                    if smoke.get("ok")
                    else {**manifest, "status": manifest.get("status", "draft")}
                )
            except Exception as reg_exc:
                smoke = dict(smoke)
                smoke["register_error"] = str(reg_exc)
            res = {
                "ok": bool(smoke.get("ok")),
                "job_id": job_id,
                "capability_slug": cap,
                "mcp_slug": mslug,
                "manifest": manifest,
                "smoke": smoke,
            }
            mark_done(job_path, res)
            results.append(res)
        except Exception as exc:
            res = {
                "ok": False,
                "job_id": job_id,
                "capability_slug": cap,
                "error": str(exc),
            }
            try:
                mark_done(job_path, res)
            except Exception:
                pass
            results.append(res)
    return results
