"""HTML report generator."""
from typing import Any


class HtmlReportGenerator:
    """Generate HTML-formatted vulnerability reports."""

    def generate(self, findings: list[dict]) -> str:
        """Return an HTML string of the findings."""
        if not findings:
            return self._empty_html()

        rows = ""
        for f in findings:
            severity = f.get("severity", "UNKNOWN")
            color = self._severity_color(severity)
            rows += f"""
            <tr>
                <td><span style="color: {color}; font-weight: bold;">{severity}</span></td>
                <td>{f.get("package", "")}</td>
                <td>{f.get("version", "")}</td>
                <td>{f.get("cve_id", "N/A")}</td>
                <td>{f.get("cvss", 0)}</td>
                <td>{f.get("description", "No description")}</td>
                <td>{f.get("fix", "No fix available")}</td>
            </tr>"""

        return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Dependency Vulnerability Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        h1 {{ color: #333; }}
        table {{ border-collapse: collapse; width: 100%; margin-top: 10px; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #4CAF50; color: white; }}
        tr:nth-child(even) {{ background-color: #f2f2f2; }}
        tr:hover {{ background-color: #ddd; }}
    </style>
</head>
<body>
    <h1>Dependency Vulnerability Report</h1>
    <p>Generated by depvuln — {len(findings)} vulnerability(ies) found.</p>
    <table>
        <thead>
            <tr>
                <th>Severity</th>
                <th>Package</th>
                <th>Version</th>
                <th>CVE ID</th>
                <th>CVSS</th>
                <th>Description</th>
                <th>Fix</th>
            </tr>
        </thead>
        <tbody>{rows}
        </tbody>
    </table>
</body>
</html>"""

    @staticmethod
    def _severity_color(severity: str) -> str:
        """Return a color for the given severity level."""
        colors = {
            "CRITICAL": "#d32f2f",
            "HIGH": "#f44336",
            "MEDIUM": "#ff9800",
            "LOW": "#4caf50",
            "UNKNOWN": "#9e9e9e",
        }
        return colors.get(severity.upper(), "#9e9e9e")

    @staticmethod
    def _empty_html() -> str:
        """Return an HTML string for when no findings are present."""
        return """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Dependency Vulnerability Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        h1 {{ color: #333; }}
    </style>
</head>
<body>
    <h1>Dependency Vulnerability Report</h1>
    <p>No vulnerabilities found. Your dependencies are clean!</p>
</body>
</html>"""
