"""YouTube Studio constants — pricing defaults."""

# Pricing defaults for YouTube Studio
YOUTUBE_PRICING_ENABLED = True
YOUTUBE_DEFAULT_CURRENCY = "USD"
YOUTUBE_MAX_TITLE_LENGTH = 60
YOUTUBE_MAX_DESCRIPTION_LENGTH = 500
YOUTUBE_MAX_TAGS_COUNT = 15
YOUTUBE_DEFAULT_POLLING_INTERVAL = 900  # seconds
YOUTUBE_DEFAULT_MARGIN_FLOOR = 0.15

# SEO defaults
YOUTUBE_DEFAULT_SEO_TITLE_SUFFIX = " - Best Price"
YOUTUBE_DEFAULT_SEO_TAGS = ["youtube", "shop", "online"]
