"""Constants for YouTube Studio."""

MAX_TITLE_LENGTH = 100
MAX_DESCRIPTION_LENGTH = 5000
MAX_TAGS = 500
MAX_KEYWORDS = 15
DEFAULT_SEO_SCORE_THRESHOLD = 50
DEFAULT_TITLE_LENGTH = 60
DEFAULT_KEYWORD_COUNT = 10
