"""PDF export for NDA contracts — uses reportlab if available, falls back to plain text."""

import io
import logging
import os
from typing import Optional

logger = logging.getLogger(__name__)

_REPORTLAB_AVAILABLE = False
try:
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
    _REPORTLAB_AVAILABLE = True
except ImportError:
    pass

DISCLAIMER = (
    "LEGAL DISCLAIMER: This document was generated by an automated tool for "
    "informational purposes only. It does NOT constitute legal advice. "
    "Always consult a qualified attorney before executing any legal agreement."
)


def export_pdf(text: str, output_path: str, title: str = "Non-Disclosure Agreement") -> str:
    """Export NDA text to a PDF file.

    Args:
        text: The contract text to export.
        output_path: The file path to write the PDF to.
        title: The document title shown in the PDF header.

    Returns:
        The output_path on success.

    Raises:
        IOError: If the file cannot be written.
    """
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    if not _REPORTLAB_AVAILABLE:
        logger.warning("reportlab not installed — falling back to plain text PDF simulation")
        return _export_plaintext(text, output_path, title)

    return _export_reportlab(text, output_path, title)


def _export_reportlab(text: str, output_path: str, title: str) -> str:
    """Render PDF via reportlab."""
    doc = SimpleDocTemplate(
        output_path,
        pagesize=LETTER,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
        title=title,
    )

    styles = getSampleStyleSheet()
    style_normal = ParagraphStyle(
        "NDANormal",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        alignment=TA_JUSTIFY,
        spaceAfter=6,
    )
    style_heading = ParagraphStyle(
        "NDAHeading",
        parent=styles["Heading1"],
        fontSize=13,
        leading=18,
        alignment=TA_CENTER,
        spaceAfter=12,
        spaceBefore=8,
    )
    style_disclaimer = ParagraphStyle(
        "NDADisclaimer",
        parent=styles["Normal"],
        fontSize=8,
        leading=11,
        textColor=colors.grey,
        alignment=TA_CENTER,
        spaceBefore=24,
    )

    story = []

    # Title
    story.append(Paragraph(title, style_heading))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.black))
    story.append(Spacer(1, 12))

    # Body — split on blank lines, treat ALL-CAPS lines as section headings
    for para in text.split("\n\n"):
        para = para.strip()
        if not para:
            continue
        if para.isupper() or (len(para) < 80 and para.endswith(":")):
            story.append(Paragraph(para, style_heading))
        else:
            # Preserve line breaks within paragraphs
            safe = para.replace("\n", "<br/>")
            story.append(Paragraph(safe, style_normal))
        story.append(Spacer(1, 4))

    # Disclaimer footer
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    story.append(Paragraph(DISCLAIMER, style_disclaimer))

    doc.build(story)
    logger.info("PDF exported: %s", output_path)
    return output_path


def _export_plaintext(text: str, output_path: str, title: str) -> str:
    """Fallback: write a plain .pdf.txt file."""
    fallback_path = output_path + ".txt"
    with open(fallback_path, "w", encoding="utf-8") as f:
        f.write(f"{title}\n{'=' * len(title)}\n\n")
        f.write(text)
        f.write(f"\n\n{DISCLAIMER}\n")
    logger.info("Plain-text fallback written to %s (reportlab not available)", fallback_path)
    return fallback_path


def pdf_to_bytes(text: str, title: str = "Non-Disclosure Agreement") -> bytes:
    """Return the PDF as bytes (in-memory). Falls back to UTF-8 encoded text."""
    if not _REPORTLAB_AVAILABLE:
        return (title + "\n\n" + text + "\n\n" + DISCLAIMER).encode("utf-8")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=LETTER, title=title)
    styles = getSampleStyleSheet()
    story = [Paragraph(title, styles["Heading1"]), Spacer(1, 12)]
    for para in text.split("\n\n"):
        para = para.strip()
        if para:
            story.append(Paragraph(para.replace("\n", "<br/>"), styles["Normal"]))
            story.append(Spacer(1, 6))
    doc.build(story)
    return buf.getvalue()
