"""DOCX export for NDA contracts — uses python-docx if available, falls back to plain text."""

import logging
import os

logger = logging.getLogger(__name__)

_DOCX_AVAILABLE = False
try:
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    _DOCX_AVAILABLE = True
except ImportError:
    pass

DISCLAIMER = (
    "LEGAL DISCLAIMER: This document was generated by an automated tool for "
    "informational purposes only. It does NOT constitute legal advice. "
    "Always consult a qualified attorney before executing any legal agreement."
)


def export_docx(text: str, output_path: str, title: str = "Non-Disclosure Agreement") -> str:
    """Export NDA text to a DOCX file.

    Args:
        text: The contract text to export.
        output_path: The file path to write the DOCX to.
        title: The document title shown as the first heading.

    Returns:
        The output_path on success.

    Raises:
        IOError: If the file cannot be written.
    """
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    if not _DOCX_AVAILABLE:
        logger.warning("python-docx not installed — falling back to plain text")
        return _export_plaintext(text, output_path, title)

    return _export_docx(text, output_path, title)


def _export_docx(text: str, output_path: str, title: str) -> str:
    """Render DOCX via python-docx."""
    doc = Document()

    # Title heading
    heading = doc.add_heading(title, level=0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Core properties
    doc.core_properties.title = title
    doc.core_properties.author = "NDA Contract Generator"

    # Body paragraphs
    for para_text in text.split("\n\n"):
        para_text = para_text.strip()
        if not para_text:
            continue

        # Detect section headings: ALL CAPS or short lines ending with ':'
        if para_text.isupper() or (len(para_text) < 80 and para_text.strip().endswith(":")):
            p = doc.add_heading(para_text.rstrip(":"), level=2)
        else:
            # Handle line breaks within paragraph
            lines = para_text.split("\n")
            p = doc.add_paragraph()
            for i, line in enumerate(lines):
                if i > 0:
                    p.add_run("\n")
                run = p.add_run(line)
                run.font.size = Pt(11)
            p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

    # Disclaimer
    doc.add_paragraph()  # spacer
    doc.add_paragraph("─" * 60)
    disclaimer_para = doc.add_paragraph(DISCLAIMER)
    disclaimer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in disclaimer_para.runs:
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x80, 0x80, 0x80)

    doc.save(output_path)
    logger.info("DOCX exported: %s", output_path)
    return output_path


def _export_plaintext(text: str, output_path: str, title: str) -> str:
    """Fallback: write a .docx.txt file."""
    fallback_path = output_path + ".txt"
    with open(fallback_path, "w", encoding="utf-8") as f:
        f.write(f"{title}\n{'=' * len(title)}\n\n")
        f.write(text)
        f.write(f"\n\n{DISCLAIMER}\n")
    logger.info("Plain-text fallback written to %s (python-docx not available)", fallback_path)
    return fallback_path
