"""
Discriminator — Classifies video frames as real or fake.

The discriminator takes a video as input and outputs a probability
that the video is real (vs. generated by the generator).
"""

import torch
import torch.nn as nn
from typing import Tuple


def _validate_tensor(tensor, name, expected_ndim, device=None):
    """Validate a tensor input for the Discriminator.

    Args:
        tensor: Input tensor to validate.
        name: Name of the parameter (for error messages).
        expected_ndim: Expected number of dimensions.
        device: Expected device.

    Raises:
        TypeError: If tensor is not a torch.Tensor.
        ValueError: If tensor has wrong shape or zero batch size.
        RuntimeError: If device doesn't match expected device.
    """
    if not isinstance(tensor, torch.Tensor):
        raise TypeError(f"{name} must be a torch.Tensor, got {type(tensor).__name__}")
    if tensor.ndim != expected_ndim:
        raise ValueError(f"{name} must have {expected_ndim} dimensions (batch, channels, frames, height, width), got {tensor.ndim}D")
    if tensor.size(0) == 0:
        raise ValueError(f"{name} batch size must be > 0, got 0")
    if device is not None and tensor.device != device:
        raise RuntimeError(f"{name} device mismatch: expected {device}, got {tensor.device}")


class Discriminator(nn.Module):
    """Video GAN Discriminator: classifies videos as real or fake."""

    def __init__(
        self,
        input_channels: int = 3,
        num_frames: int = 16,
        frame_size: int = 64,
    ):
        """
        Args:
            input_channels: Number of channels in input frames.
            num_frames: Number of frames in the video sequence.
            frame_size: Spatial size of each frame.
        """
        super().__init__()

        self.main = nn.Sequential(
            # Input: (batch, channels, frames, height, width)
            nn.Conv3d(input_channels, 64, kernel_size=(3, 4, 4), stride=(1, 2, 2), padding=(1, 1, 1)),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Dropout3d(0.25),
            # (64, frames-2, height/2, width/2)

            nn.Conv3d(64, 128, kernel_size=(3, 4, 4), stride=(1, 2, 2), padding=(1, 1, 1)),
            nn.BatchNorm3d(128),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Dropout3d(0.25),
            # (128, frames-4, height/4, width/4)

            nn.Conv3d(128, 256, kernel_size=(3, 4, 4), stride=(1, 2, 2), padding=(1, 1, 1)),
            nn.BatchNorm3d(256),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Dropout3d(0.25),
            # (256, frames-6, height/8, width/8)

            nn.Conv3d(256, 1, kernel_size=(3, 4, 4), stride=(1, 2, 2), padding=(1, 1, 1)),
            # (1, frames-8, height/16, width/16) — raw logits (no sigmoid)
        )

        # Global average pooling to get a single score per sample
        self.pool = nn.AdaptiveAvgPool3d(1)

    @property
    def device(self) -> torch.device:
        """Return the device of the first parameter."""
        return next(self.parameters()).device

    def forward(self, video: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """Classify video as real or fake.

        Args:
            video: Video tensor of shape (batch, channels, frames, height, width).

        Returns:
            real_scores: Raw logits (before sigmoid), shape (batch, 1).
            features: Intermediate feature map, shape (batch, 1, frames-8, h/16, w/16).

        Raises:
            TypeError: If video is not a torch.Tensor.
            ValueError: If video has wrong shape or zero batch size.
            RuntimeError: If video device doesn't match model device.
        """
        _validate_tensor(video, "video", 5, self.device)

        features = self.main(video)
        real_scores = self.pool(features)
        real_scores = real_scores.view(real_scores.size(0), -1)
        # Apply sigmoid to get probabilities in [0, 1]
        real_scores = torch.sigmoid(real_scores)
        return real_scores, features
